version: "3.8"

services:
  app-elasticsearch:
    container_name: stac-fastapi-elasticsearch
    image: cedadev/stac-fastapi-elasticsearch
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - STAC_ELASTICSEARCH_SETTINGS=flexi_settings.settings
      - DJANGO_FLEXI_SETTINGS_ROOT=/app/conf/settings.py
      - APP_HOST=0.0.0.0
      - APP_PORT=8081
    ports:
      - 8081:8081
    volumes:
      - ./stac_fastapi:/app/stac_fastapi
      - ./scripts:/app/scripts
      - ./conf:/app/conf
      - ./tests:/app/tests
    depends_on:
      - database
    command: bash -c "./scripts/wait-for-it.sh database:9200 -t 60 && python -m stac_fastapi.elasticsearch.run"
  database:
    container_name: stac-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    environment:
      - node.name=es01
      - cluster.name=stac-cluster
      - discovery.type=single-node
      - network.host=0.0.0.0
      - http.port=9200
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
  loadsample-elasticsearch:
    image: cedadev/stac-fastapi-elasticsearch
    volumes:
      - ./stac_fastapi:/app/stac_fastapi
      - ./scripts:/app/scripts
    command: bash -c "./scripts/wait-for-it.sh database:9200 -t 60 && python /app/scripts/ingest_test_data.py --host http://database:9200"
    depends_on:
      - database
      - app-elasticsearch

networks:
  default:
    name: stac-fastapi-elasticsearch-network
