name: stac-fastapi-elasticsearch

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      db_service:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
        env:
          node.name=es01
          cluster.name=stac-cluster
          discovery.type=single-node
          network.host=0.0.0.0
          http.port=9200
          "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
          - 9200:9200
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: install requirements
        run: |
          pip install -r ./requirements.txt

      - name: Install elasticsearch stac-fastapi
        run: |
          pip install .[dev,server]

      - name: Run test suite
        run: |
          pipenv run pytest -svvv
        env:
          STAC_ELASTICSEARCH_SETTINGS=flexi_settings.settings
          DJANGO_FLEXI_SETTINGS_ROOT=/app/conf/settings.py
          APP_HOST=0.0.0.0
          APP_PORT=8081

